services:    
  rust_lesson:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_lesson
    volumes:
      - ..:/lesson
      - /lesson/target
    ports:
      - "8001:8001"
    
